# Generated by Django 4.2.1 on 2023-05-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_darah', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengguna',
            name='id',
        ),
        migrations.AddField(
            model_name='pengguna',
            name='user_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
